project:
  type: website
execute: 
  freeze: auto

website:
  title: "Prasaath's Blog"
  image: me.png
  favicon: me.png
  navbar:
    logo: me.png
    pinned: true
    right:
      - href: https://prasaath-sastha.github.io/
        text: About me
      - icon: github
        text: Github
        href: https://github.com/prasaath-sastha
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/prasaathsastha/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

